[workspace]
channels = ["conda-forge"]
name = "depthPlane"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
sam3 = "python -m pip install -e submodules/sam3"

[dependencies]
python = "3.12.*"
open3d = ">=0.19.0,<0.20"
pip = ">=25.3,<26"
einops = ">=0.8.1,<0.9"
pythonocc-core = "7.9.*"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://download.pytorch.org/whl/cu126"]

[pypi-dependencies]
scikit-spatial = ">=9.0.1, <10"
laspy = ">=2.6.1, <3"
lazrs = ">=0.8.0, <0.9"
numpy = ">=2.3.3, <3"
matplotlib = ">=3.10.7, <4"
pytest = ">=9.0.1, <10"
pyyaml = ">=6.0.3, <7"
einops = ">=0.8.1, <0.9"
decord = ">=0.6.0, <1"
pycocotools = ">=2.0.8, <3"
psutil = ">=5.9.8, <6"
torch = "==2.7.0"
torchvision = "*"
torchaudio = "*"
